apiVersion: v1
kind: ServiceAccount
metadata:
  name: func-deployer
  namespace: default
imagePullSecrets:
  - name: regcred

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvc-manager
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get","list","watch","create","delete","update","patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pvc-manager-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: func-deployer
    namespace: default
roleRef:
  kind: Role
  name: pvc-manager
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: func-deployer-tekton
  namespace: default
rules:
  # Allow managing Tekton pipelines & runs
  - apiGroups: ["tekton.dev"]
    resources:
      - pipelines
      - pipelineruns
      - tasks
      - taskruns
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: func-deployer-tekton-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: func-deployer
    namespace: default
roleRef:
  kind: Role
  name: func-deployer-tekton
  apiGroup: rbac.authorization.k8s.io

