apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: tonylab-worker
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2025-06-25T20:48:45Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    function.knative.dev/name: springfn
    function.knative.dev/runtime: springboot
  name: springfn-pack-git-pipeline-pvc
  namespace: default
  resourceVersion: "2088826"
  uid: 212f584c-73f6-430f-a000-b7951e1f2c98
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-212f584c-73f6-430f-a000-b7951e1f2c98
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 256Mi
  phase: Bound
